# Generated by Django 5.2.7 on 2025-12-01 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='principal',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='department',
        ),
    ]
